### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by bobemoe** [hdus/SRTM-Downloader#1]
When installing the plugin I get the following error:

```
The plugin is broken. Python said:
No module named request
```

I have installed ```request``` using pip, and can confirm it does not throw error in QGIS console when typing ```import request;``` so I do not know what to try next?

Running on Linux: Devuan 2.0 (Debian Stretch based)

QGIS version | 2.14.11-Essen | QGIS code branch | Release 2.14
Compiled against Qt | 4.8.7 | Running against Qt | 4.8.7
Compiled against GDAL/OGR | 2.1.2 | Running against GDAL/OGR | 2.1.2
Compiled against GEOS | 3.5.1-CAPI-1.9.1 | Running against GEOS | 3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version | 9.6.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.2 | PROJ.4 Version | 493
QScintilla2 Version | 2.9.3 |

**Comment by hdus** [comment]
I can not reproduce this error. It works for me with QGIS 2.14, 2.18 and QGIS 3
