### ISSUE TITLE
"Plugin has disappeared" error

### ISSUE THREAD

**Issue by barryrowlingson** [hdus/SRTM-Downloader#11]
If I try and install the SRTM Downloader in a new user profile in QGIS 3.10 I can see the plugin in the list, I can select it and click "install Plugin" but then I get this error:

```
Plugin has disappeared: The plugin seems to have been installed but I don't know where. Probably the plugin package contained a wrong named directory. Please search the list of installed plugins. I'm nearly sure you'll find the plugin there, but I just can't determine which of them it is. It also means that I won't be able to determine if this plugin is installed and inform you about available updates. However the plugin may work. Please contact the plugin author and submit this issue.
```

The plugins dialog then shows it twice (once with its nasa icon and once with the default jigsaw piece icon) but I don't see any menu options for it and trying to *un*install it gives a: 

```
Are you sure you want to uninstall the following plugin?
(SRTM Downloader)

Warning: this plugin isn't available in any accessible repository!
```

An `SRTM-Downloader` folder is created in the profiles python/plugins folder, so I'm mystified as to what the problem is...

**Comment by barryrowlingson** [comment]
Changing metadata.txt to have:
```
name=SRTM-Downloader
```

instead of 

```
name=SRTM Downloader
```

seems to help (although I think now QGIS doesn't think my modified SRTM Downloader is the same as the one in the repository because the name is different).

**Comment by Bernd-Vogelgesang** [comment]
Seems I'm to stupid to do the trick. Not able to get it showing up.

**Comment by hdus** [comment]
I is fixed like Barry mentioned.
