### ISSUE TITLE
local variable 'lat_tx' referenced before assignment

### ISSUE THREAD

**Issue by LGBudd** [hdus/SRTM-Downloader#13]
Upon clicking the Download button, get this error:
File "C:/Users/Username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SRTM-Downloader\srtm_downloader_dialog_base.py", line 147, in get_tiles
              url = "https://e4ftl01.cr.usgs.gov//MODV6_Dal_D/SRTM/SRTMGL1.003/2000.02.11/%s%s.SRTMGL1.hgt.zip" % (lat_tx, lon_tx)
             UnboundLocalError: local variable 'lat_tx' referenced before assignment

QGIS version | 3.10.3-A Coruña
Python 3.7
Windows 10 Home V 1909

**Comment by hdus** [comment]
Please send the boundingbox of the area of download.

**Comment by hdus** [comment]
No response. Issue closed.
