### ISSUE TITLE
Doesn't work for latitude value of -10

### ISSUE THREAD

**Issue by ttrinidad** [hdus/SRTM-Downloader#15]
It ignores any tiles from lat -10 due to a mistake in the following line:
https://github.com/hdus/SRTM-Downloader/blob/e32b747bb5773adeff31ec83a45090e96c787d51/srtm_downloader_dialog_base.py#L146

It should read `lat <= -10`

**Comment by hdus** [comment]
It is fixed, please give it a try.

**Comment by ttrinidad** [comment]
It works, thanks.
