### ISSUE TITLE
L'AREA DELL'ISLANDA NON MI RESTITUISCE I VALORI RICHIESTI

### ISSUE THREAD

**Issue by angelorosa100** [hdus/SRTM-Downloader#18]
PERCHE' LAREA DELL'ISLANDA NON RESTITUISCE I VALORI E LE IMMAGINI ?

**Comment by hdus** [comment]
THAT IS EASY TO EXPLAIN. ICELAND IS NOT COVERED BY THE SRTM MISSION!!!
