### ISSUE TITLE
TypeError when attempting to download map data.

### ISSUE THREAD

**Issue by AbrarSL** [hdus/SRTM-Downloader#20]
`2021-04-26T11:26:47     WARNING    Traceback (most recent call last):
              File "C:/Users/Fuwad/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SRTM-Downloader\download.py", line 105, in reply_finished
              (dir, file) = os.path.split(out_image)
              File "C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\ntpath.py", line 183, in split
              p = os.fspath(p)
             TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by AbrarSL** [comment]
It seems like this was the result of a server issue and not an issue with the plugin. Closing. Sorry about any trouble.

**Comment by bstrombergHUD** [comment]
This doesn't seem resolved. I just installed this a few minutes ago and I'm getting the same error when I try to use it. Is there something I can do on the user's side to get it to work?
