### ISSUE TITLE
Option to stop asking user for username and password 

### ISSUE THREAD

**Issue by RobinKohrs** [hdus/SRTM-Downloader#23]
I sometimes run into the issue that I want to qurey SRTM Data for a larger region without thinking that I might not remember my username and password. If I query, lets say 100 tiles, it will ask me 100 times for my username and password. Up to now I just always quitted QGis at this point. Am I missing something or is this maybe worth an idea to imlement? 
Sorry I use this amazing plugin very rarely so might be a stupid question...

**Comment by hdus** [comment]
This should not happen. Does it still persist. Please send the plugin version.
