### ISSUE TITLE
Error when trying to download data. 

### ISSUE THREAD

**Issue by jendahorak** [hdus/SRTM-Downloader#24]
I am able to login into my Earthdata User Profile but after that it returns this error:

Error transferring https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/S64W058.SRTMGL1.hgt.zip - server replied: Not Found

![obrazek](https://user-images.githubusercontent.com/70900705/155686624-aeab80f5-6260-4ee8-8bc7-bf57d2bb9420.png)

**Comment by hdus** [comment]
The selected area is not covered by SRTM data. Please look here:
https://dwtkns.com/srtm30m/

**Comment by jendahorak** [comment]
oh.. my bad, thanks
