### ISSUE TITLE
Plugin not working at all.

### ISSUE THREAD

**Issue by AtraX04** [hdus/SRTM-Downloader#31]
**UPDATE: NOW IT WORKS AS IT SHOULD!**
Thank you!
-
-
-
Hello!

Im trying to create a DEM merging few images that are available for my region that I want and its simply not working. Ive tried the plugin few days ago but when I saw that I have to create an account Ive told to my self I will just do it later. Now that I am here trying again, that window that says me to create an account does not pop anymore. (I have also watched some youtube videos about the plugin but none helped me). I will attach some immages.

![Captură de ecran 2024-01-10 213044](https://github.com/hdus/SRTM-Downloader/assets/156240239/fda0388f-6db4-45ed-a015-199fab664745)
![Captură de ecran 2024-01-10 212957](https://github.com/hdus/SRTM-Downloader/assets/156240239/7902fb8d-4a01-4688-a824-791395b40068)
![Captură de ecran 2024-01-10 215937](https://github.com/hdus/SRTM-Downloader/assets/156240239/ae488f57-0dc0-4c0d-a7d5-96644bd64cd6)

QGIS version
3.28.2-Firenze

Plugin version
3.2.1

**Comment by hdus** [comment]
Do you connect to the internet through a proxy?

**Comment by AtraX04** [comment]
> Do you connect to the internet through a proxy?

No, I am not.
