### ISSUE TITLE
Unable to Download Data

### ISSUE THREAD

**Issue by rosavargasv** [hdus/SRTM-Downloader#33]
Hi,

I'm encountering an issue with the SRTM-Downloader. The application prompts me to log in to Earthdata, which I do, but the download fails and shows the following errors.

Here’s what happens:

1. The downloader indicates that the download is complete.

![image_2024-08-20_113622392](https://github.com/user-attachments/assets/38c87547-c61c-4210-9540-5a1c43dd4be1)

2. However, I receive the following error messages indicating authentication issues:

![image](https://github.com/user-attachments/assets/a5a4b1c4-6c08-4106-8a51-718590a3984c)
![image](https://github.com/user-attachments/assets/7d6058c3-9946-4de6-b60a-617a1c995daf)

Here are the details of my setup:

SRTM-Downloader Version: 3.2.2
QGIS Version: 3.34.1-Prizren
QGIS Code Revision: 133927424d
Qt Version: 5.15.3
Python Version: 3.9.5
GDAL/OGR Version: 3.8.1
PROJ Version: 9.3.1
EPSG Registry Database Version: v10.098 (2023-11-24)
GEOS Version: 3.12.1-CAPI-1.18.1
SQLite Version: 3.41.1
PDAL Version: 2.6.0
PostgreSQL Client Version: Unknown
SpatiaLite Version: 5.1.0
QWT Version: 6.1.6
QScintilla2 Version: 2.13.4
OS Version: Windows 10 Version 2009

Could you please help me resolve this issue?
Thank you!

**Comment by hdus** [comment]
The Issue is duplcated #30
