### ISSUE TITLE
Infinite loop of auth dialog

### ISSUE THREAD

**Issue by kannes** [hdus/SRTM-Downloader#4]
If one tries to use the plugin without having an account for the download site, the plugin will infinitely re-show the login dialog until the user decides to lose their work and just kill the QGIS process. This is BAD. Please let users cancel the plugin.

**Comment by dpsspatial** [comment]
+1...

**Comment by JakubSisak** [comment]
+1

**Comment by lgoldsto** [comment]
Ditto with what kannes said. Same thing happened to me. Please fix.

**Comment by hdus** [comment]
It's a hobby project of mine and I have no resources to fix it at the next time. Please feel free to fix the issue and send me a pull request.

**Comment by Marwe** [comment]
I even created such an account and it did not work. 
Basically it should *not be a modal* dialog, because then you can only kill qgis and loose any work not saved...
And "cancel" should work = end dialog ;)

**Comment by hdus** [comment]
Fixed in Revision 3.0.0 for QGIS 3.

**Comment by kannes** [comment]
Thank you!
