### ISSUE TITLE
Lost Login box

### ISSUE THREAD

**Issue by Fordonian** [hdus/SRTM-Downloader#6]
Have upgraded to 3.6 and seem to have lost the login box - it goes to run but never presents the box. I've another machine still running 3.4.2 which does still show the box so I'm guessing it's probably version dependent. Will roll back to 3.4 for now, more just letting you know!

**Comment by hdus** [comment]
Fixed in revision 3.1.2. QgsNetworkAccessmanager seems to be buggy. Changed it to QNetworkAccessManager. Maybe you can get trouble with proxy settings. Please let me know if it happens.

**Comment by Fordonian** [comment]
Updated this morning and looks to be working - getting the box but there’s a good chance I put my password in wrong - will have more of a play with it over the weekend when the day job isn’t getting in the way! 

Thanks for the update, it’s a great plugin!
