### ISSUE TITLE
credentials request dialogue not appearing on new install ver 3.14

### ISSUE THREAD

**Issue by damstep** [hdus/SRTM-Downloader#9]
Hi I have used you SRTM downloader on another machine and it works well thankyou.
I just installed qgis 3.6.3 on a new win 10 machine and installed your plugin (3.14) without error.
when i went to use it, it picked the area i wanted usinghte canvas extent button and chose one tile to download, however the request for credential dialogue did not appear. The download progress bar went immediately to 100% , but the progress for the tiles is still empty.
I checked the download location ad there is nothing there.
I reinstalled the plugin.
and tried every combination of load when done, save to temporary file etc.
Hope this helps
thanks
Damien

**Comment by UnityGISTech** [comment]
I have the same issus

**Comment by UnityGISTech** [comment]
Solution : 

Ok, this is slightly embarrassing but I'll post the answer here anyway in case someone is as blind as I was. Apparently, there are two QGIS executable files: C:\OSGeo4W64\bin\qgis-bin.exe and C:\OSGeo4W64\bin\qgis-bin-g7.4.1.exe. In Windows, when firing up a program via the Windwos startup button, it runs qgis-bin.exe by default and GRASS does not work. When you run qgis-bin-g7.4.1.exe however, it GRASS works.

**Comment by hdus** [comment]
At the moment I'm not able to fix this issue and any other issues due to I'm on a sabbatical around the world. I would appreciate any posted fixes or pull requests.
